### PR TITLE
accept 'signet' as LND_ENVIRONMENT variable

### PR DESCRIPTION
**Pull request by sgiammy**

### CODE REVIEW

**Comment by sgiammy-rta** [comment]
any update on this one?

**Comment by sgiammy** [comment]
any update on this one?

**Review by dennisreimann — APPROVED** [review]
LGTM, thanks! Final ACK, @rockstardev?

**Comment by NicolasDorier** [comment]
Sorry @sgiammy  just saw that now, I think it's good to include this

**Pull request merged**
